"""
Django settings for bein_sports project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4att9pw=cu93mb3!g38s^mfwbh+flhk5a!5zd+jrwz8eh15&n%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_crontab',
    'django.contrib.staticfiles',
    'middleware',
    'rest_framework',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bein_sports.urls'
DATETIME_DISPLAY_FORMAT = "%Y-%m-%d %H:%M:%S"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

''' eMAM Configuration Settings '''
WSGI_APPLICATION = 'bein_sports.wsgi.application'
EMAM_GATEWAY_WSDL = ''  # http://{ip or domain}/eMAMgateway/emamservice.asmx?wsdl
EMAM_USERNAME = ''  # eMAM user has to be a UNIT Admin
EMAM_PASSWORD = ''
UNIT_ID = ''
LICENSE_KEY = ''  # You can find it on Registry Editor ("HKEY_LOCAL_MACHINE/eMAM Gateway/ComponentLicenseKey") of eMAM Server
METADATA_GROUP_ID = ''
USER_KEY = ''
FILE_ACTION = 'move'  # Action done with media asset while XML ingest, can be copy-file/move/index
SET_STANDARD_ID = ''

# Ingest Actions
INGEST_ACTIONS = {
    'CREATE_NEW_ASSET' : 'create-new-asset',
    'ASSOCIATE_METADATA' : 'associate-metadata',
    'CREATE_NEW_VERSION' : 'create-new-version',
    'CREATE_ASSET_PLACEHOLDER' : 'create-asset-placeholder'
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'middleware',
        'USER': 'middleware',
        'PASSWORD': 'admin',
        'HOST': 'localhost'
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

USE_TZ = False

TIME_ZONE = 'Asia/Calcutta'

# Mail settings
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587
EMAIL_RECEIVER = 'SGP-APAC-Mediaops@bein.net'

# Folder names/paths
# Need to fill out following paths/names before running the app.
EMAM_CATEGORY_ROOT_FOLDER = '01_Original Masters'
ROOT_FOLDER_PATH = '' # Directory path where watch, error, media, processing folders resides.
XML_WATCH_FOLDER_NAME = '' # Name of XML watch folder
EMAM_INGEST_FOLDER_FULL_PATH = '' # Full path of XML ingest folder / You can find it on associated eMAM ingest profile.
ERROR_FOLDER_NAME = '' # Name of XML error folder / It will be used by scheduler while validating XML.
PROCESSING_FOLDER_NAME = '' # Name of processing folder / It will be used by scheduler while validating XML.

# Video sub-folders names
VIDEO_FOLDER_NAMES = []

#Folder paths
PATH_TO_WATCH_FOLDER_XMLS = ROOT_FOLDER_PATH + '/' + XML_WATCH_FOLDER_NAME + '/*.xml'
PATH_TO_PROCESSING_FOLDER = ROOT_FOLDER_PATH + '/' + PROCESSING_FOLDER_NAME
PATH_TO_ERROR_FOLDER = ROOT_FOLDER_PATH + '/' + ERROR_FOLDER_NAME

# House_id
HOUSE_ID = '' # Metadata field used for identification of XML.

#CONTENT-TYPE
CONTENTTYPE = ''

#Opta_id
OPTA_ID = ''

#SOM id
SOM_ID = ''

#Marker duration
MARKER_DURATION='00:00:00:00' #Do not change the format.

'''Required to update score custom-metadata in eMAM'''
#SCORE id
SCORE_ID = '' # eMAM custom standard_id

# No. of times scheduler should OMO pull.
OMO_PULL_FREQUENCY = 2

# Time span between OMO pulls
GAP_BETWEEN_OMO_PULLS = 2 # in minutes

# SOM values
SOM_VALUES ={
    'f13_second_half' : '00:15:00:00' # Set to 15 min for football second half f13 feed.
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'

CRONTAB_LOCK_JOBS = True
# CELERY SETTINGS
BROKER_URL = 'amqp://localhost:5672'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%b %d, %Y %H:%M:%S"
        }
    },
    'handlers': {
        'production': {
            'level': 'INFO',
            'filename': os.path.join(BASE_DIR, 'logs', 'emam.log'),
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': 15728640,
            'backupCount': 10,
            # 'when': 'midnight',
            # 'interval': 1,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'middleware': {
            'handlers': ['production'],
            'level': 'INFO'
        },
    },
}

