# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('message', models.CharField(max_length=254, verbose_name='comment')),
                ('opta_id', models.CharField(blank=True, default='', max_length=50)),
                ('asset_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('converted_xml', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Basic Xml',
                'verbose_name_plural': 'Basic Xmls',
            },
        ),
        migrations.CreateModel(
            name='MetadataAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field_name', models.CharField(max_length=20)),
                ('original_filed_name', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('unit_id', models.PositiveSmallIntegerField(blank=True, default=None)),
                ('is_active', models.BooleanField(default=1)),
                ('is_required', models.BooleanField(default=1)),
                ('field_description', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metadata Attributes',
                'verbose_name_plural': 'Metadata Attributes',
            },
        ),
        migrations.CreateModel(
            name='OptaXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opta_id', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('message', models.CharField(max_length=254, verbose_name='comment')),
                ('converted_xml', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Opta Xml',
                'verbose_name_plural': 'Opta Xmls',
            },
        ),
    ]
