# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optaxml',
            name='status',
        ),
        migrations.AddField(
            model_name='metadataattributes',
            name='field_type',
            field=models.CharField(blank=True, choices=[('Text', b'Text'), ('Time Code', b'Time_Code')], default='Text', max_length=20),
        ),
        migrations.AddField(
            model_name='metadataattributes',
            name='visibility',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='optaxml',
            name='sta296tus',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
