# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_auto_20171114_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optaxml',
            old_name='sta296tus',
            new_name='status',
        ),
    ]
