# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0003_auto_20171114_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataattributes',
            name='custom_field_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadataattributes',
            name='field_type',
            field=models.CharField(blank=True, choices=[('Text', b'Text'), ('TimeCode', b'Time_Code')], default='Text', max_length=20),
        ),
        migrations.AlterField(
            model_name='metadataattributes',
            name='original_filed_name',
            field=models.CharField(max_length=50),
        ),
    ]
