# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0005_auto_20171116_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataattributes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='metadataattributes',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='metadataattributes',
            name='user',
        ),
    ]
