# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0007_auto_20171121_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicxml',
            name='status',
            field=models.CharField(blank=True, choices=[('converted', b'Converted'), ('error', b'Error'), ('ingested', b'Ingested'), ('ingesting', b'Ingesting'), ('pending', b'Pending'), ('processing', b'Processing')], default='pending', max_length=20),
        ),
    ]
