# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0008_auto_20171123_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicxml',
            name='parent_id',
            field=models.IntegerField(default=None),
        ),
    ]
