# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0009_basicxml_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicxml',
            name='parent_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
