# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0010_auto_20171123_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicXmlLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('converted', b'Converted'), ('error', b'Error'), ('pending', b'Pending'), ('posted', b'Posted'), ('processing', b'Processing')], default='pending', max_length=20)),
                ('logs', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='basicxml',
            name='message',
        ),
        migrations.RemoveField(
            model_name='basicxml',
            name='status',
        ),
        migrations.AddField(
            model_name='basicxmllogs',
            name='basic_xml_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middleware.BasicXml'),
        ),
    ]
