# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0011_auto_20171129_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicxmllogs',
            options={'verbose_name': 'Basic Xml Logs', 'verbose_name_plural': 'Basic Xml Logs'},
        ),
    ]
