# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0012_auto_20171129_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicxmllogs',
            old_name='basic_xml_id',
            new_name='basic_xml',
        ),
        migrations.RenameField(
            model_name='basicxmllogs',
            old_name='logs',
            new_name='log',
        ),
        migrations.RemoveField(
            model_name='basicxml',
            name='converted_xml',
        ),
        migrations.RemoveField(
            model_name='basicxml',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='basicxmllogs',
            name='converted_xml',
            field=models.TextField(default=''),
        ),
    ]
