# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0014_auto_20171219_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptaXmlUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_xml', models.TextField(default='')),
                ('is_completed', models.BooleanField(default=0)),
                ('log', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Opta Xml Updates',
                'verbose_name_plural': 'Opta Xml Update',
            },
        ),
        migrations.AlterField(
            model_name='optaxml',
            name='opta_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='optaxmlupdates',
            name='opta_xml',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='middleware.OptaXml'),
        ),
    ]
