# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0016_auto_20180228_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optaxml',
            name='converted_xml',
        ),
        migrations.RemoveField(
            model_name='optaxmlupdates',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='optaxml',
            name='is_completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='optaxmlupdates',
            name='last_update_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='optaxmlupdates',
            name='raw_xml',
            field=models.TextField(default=''),
        ),
    ]
