# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0017_auto_20180305_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicxml',
            name='som',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
