# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0019_optaxml_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optaxmlupdates',
            name='last_update_timestamp',
        ),
        migrations.AddField(
            model_name='optaxml',
            name='last_update_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
