# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0021_auto_20180314_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optaxml',
            name='message',
        ),
    ]
