# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0022_remove_optaxml_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optaxml',
            name='status',
        ),
        migrations.RemoveField(
            model_name='optaxmlupdates',
            name='raw_xml',
        ),
        migrations.AddField(
            model_name='optaxml',
            name='home_away_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
